# Generated by Django 3.1.7 on 2021-03-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='images',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
